// Code generated by scripts/zk_registry/gnark_instantiation.py; DO NOT EDIT.

package wrappers

import (
	"boole.local/gnarkx/harness"
	p_ecc "github.com/consensys/gnark-crypto/ecc"
	"github.com/consensys/gnark/frontend"
	p_booletoy "github.com/consensys/gnark/std/booletoy"
)

type W0b0e1e70a700_0 struct {
	In1 frontend.Variable `gnark:",secret"`
	In2 frontend.Variable `gnark:",secret"`
}

func (c *W0b0e1e70a700_0) Define(api frontend.API) error {
	r0 := p_booletoy.Toy(api, c.In1, c.In2)
	return harness.Expose(api, &r0)
}

func init() {
	harness.Register(harness.Spec{ID: "w0b0e1e70a700_0", Field: p_ecc.BN254.ScalarField(), Curve: "bn254", New: func() frontend.Circuit {
		return &W0b0e1e70a700_0{}
	}})
}
