"""Lean emitters for gnark DET packages.

The model is the R1CS template of the Circom generator (:mod:`lean_emit`): ``p``, ``F := ZMod p``,
``nWires``, literal ``Inputs`` / ``Outputs`` wire lists and ``Constraints w`` (``w 0 = 1`` and every
``(A·w) * (B·w) = C·w``, balanced coefficients, ``Block<k>`` chunks), transcribed from gnark's
compiled constraint system (the model assembled by :mod:`gnark_r1cs`).

Outputs of a wrapper are the wires exposed for the gadget's results.  Results that are emulated field
elements (``emulated.Element[T]``: limbs of ``bits`` bits, least significant first, value taken modulo
the emulated modulus) are compared as field elements, not limb by limb, since gnark does not keep
them in a canonical representation: the model lists them in ``EmulatedOutputs`` (limb wires, limb width,
modulus) with ``emValue w limbs bits = Σ val(w limb_i) * 2^(bits*i)``, and the statement is

    ∀ w₁ w₂, Constraints w₁ → Constraints w₂ → (∀ i ∈ Inputs, w₁ i = w₂ i) →
      (∀ o ∈ Outputs, w₁ o = w₂ o) ∧
        ∀ g ∈ EmulatedOutputs, emValue w₁ g.1 g.2.1 % g.2.2 = emValue w₂ g.1 g.2.1 % g.2.2

where ``Outputs`` are the native outputs.  Without emulated outputs the statement is exactly the
Circom template's.
"""
from __future__ import annotations

from typing import Sequence

from . import lean_emit as E

STATEMENT_THEOREM = E.STATEMENT_THEOREM
LEAN_OPTIONS = E.LEAN_OPTIONS
STATEMENT_PROP_EM = ("∀ w₁ w₂ : Fin nWires → F, Constraints w₁ → Constraints w₂ →\n"
                     "      (∀ i ∈ Inputs, w₁ i = w₂ i) →\n"
                     "      (∀ o ∈ Outputs, w₁ o = w₂ o) ∧\n"
                     "        ∀ g ∈ EmulatedOutputs, emValue w₁ g.1 g.2.1 % g.2.2 = emValue w₂ g.1 g.2.1 % g.2.2")
EM_FLATTEN = ["EmulatedOutputs", "emValue", "List.foldr", "List.foldr_cons", "List.foldr_nil"]

model_module = E.model_module
model_relpath = E.model_relpath


def theorem_signature(emulated: bool) -> str:
    return f" {E.STATEMENT_BINDERS} :\n    {STATEMENT_PROP_EM if emulated else E.STATEMENT_PROP}"


def emit_model(ns: str, meta: dict, r, inputs: Sequence[int], native_outputs: Sequence[int],
               groups: Sequence[tuple[list[int], int, int]], wire_names: Sequence[str | None]) -> str:
    p = r.prime
    header = [
        "import Mathlib",
        "",
        "/-!",
        f"# DET model: {meta['repo_id']} `{meta['instantiation']}`",
        "",
        f"Generated by `scripts/zk_registry` ({meta['generator']}); do not edit.",
        "",
        f"* Source: {meta['repo_url']} at `{meta['commit']}`, `{meta['path']}`, `{meta['template']}`,",
        f"  wrapper `{meta['wrapper_id']}` (rule `{meta['rule']}`): {meta['call']}.",
        f"* Compiled by gnark {meta['gnark_version']} (`frontend.Compile` with its R1CS builder, Go {meta['go_version']}),",
        f"  native field of {meta['curve']}; range checks through gnark's own non-commitment checker.",
        f"* Commitment model: {meta['commitment']}.",
        f"* Model R1CS sha256 `{meta['r1cs_sha256']}`.",
        "* `w : Fin nWires → F` gives a value to every wire; wire 0 is the constant one.",
        "* `Constraints w` holds iff `w 0 = 1` and every R1CS constraint `(A·w) * (B·w) = C·w` holds.",
        "  Coefficients are printed balanced (`c > p/2` as `-(p - c)`) and a product with an empty",
        "  factor as `0`; both preserve values in `ZMod p`.",
        "",
        "## Wires",
        "",
    ]
    for wire in range(r.n_wires):
        header.append(f"* `w {wire}`: `{wire_names[wire] or '(internal)'}`")
    header += ["-/", "", f"namespace {ns}", ""]
    body = [
        f"/-- The native field order ({meta['curve']} scalar field). -/",
        f"abbrev p : ℕ := {p}",
        "",
        "/-- Wire values. -/",
        "abbrev F : Type := ZMod p",
        "",
        "/-- Number of R1CS wires (wire 0 is the constant one). -/",
        f"abbrev nWires : ℕ := {r.n_wires}",
        "",
        *E._long_list_option(native_outputs),
        f"/-- Native outputs of the wrapper ({len(native_outputs)} wires exposing the gadget's results). -/",
        f"def Outputs : List (Fin nWires) := {E._list_literal(native_outputs)}",
        "",
        *E._long_list_option(inputs),
        f"/-- Inputs of the wrapper: every public and secret wire ({len(inputs)}). -/",
        f"def Inputs : List (Fin nWires) := {E._list_literal(inputs)}",
        "",
    ]
    if groups:
        items = ", ".join(f"({E._list_literal(limbs)}, {bits}, {mod})" for limbs, bits, mod in groups)
        body += [
            "/-- Integer value of little-endian limbs of `bits` bits each. -/",
            "def emValue (w : Fin nWires → F) (limbs : List (Fin nWires)) (bits : ℕ) : ℕ :=",
            "  limbs.foldr (fun i acc => (w i).val + 2 ^ bits * acc) 0",
            "",
            "set_option maxRecDepth 100000 in",
            f"/-- Emulated outputs ({len(groups)}): (limb wires, limb width, emulated modulus); compared modulo the modulus. -/",
            f"def EmulatedOutputs : List (List (Fin nWires) × ℕ × ℕ) := [{items}]",
            "",
        ]
    cons = [E.render_constraint(a, b, c, p) for a, b, c in r.constraints]
    blocks = E.block_names(len(cons))
    if blocks:
        for k, name in enumerate(blocks):
            chunk = cons[k * E.BLOCK:(k + 1) * E.BLOCK]
            body.append(f"/-- R1CS constraints {k * E.BLOCK}–{k * E.BLOCK + len(chunk) - 1}. -/")
            body.append(f"def {name} (w : Fin nWires → F) : Prop :=")
            body.append(" ∧\n".join(f"  {c}" for c in chunk))
            body.append("")
        body.append(f"/-- The compiled constraint system ({len(cons)} constraints). -/")
        body.append("def Constraints (w : Fin nWires → F) : Prop :=")
        body.append("  w 0 = 1 ∧ " + " ∧ ".join(f"{b} w" for b in blocks))
    else:
        body.append(f"/-- The compiled constraint system ({len(cons)} constraints). -/")
        body.append("def Constraints (w : Fin nWires → F) : Prop :=")
        body.append(" ∧\n".join(["  w 0 = 1"] + [f"  {c}" for c in cons]))
    body += ["", f"end {ns}", ""]
    return "\n".join(header + body)


def emit_statement(ns: str, meta: dict, emulated: bool) -> str:
    rel = ("agree on every native output wire and on the value of every emulated output modulo its modulus"
           if emulated else "agree on every output wire")
    return "\n".join([
        f"import {model_module(ns)}",
        "",
        f"namespace {ns}",
        "",
        f"/-- Output determinism of {meta['repo_id']} `{meta['instantiation']}` ({meta['path']}): two",
        "assignments that satisfy the compiled constraints and agree on every input wire",
        f"{rel}. -/",
        f"theorem {STATEMENT_THEOREM}{theorem_signature(emulated)} := by",
        "  sorry",
        "",
        f"end {ns}",
        "",
    ])


def unfold_order(n_constraints: int, emulated: bool) -> list[str]:
    em = ["EmulatedOutputs", "emValue"] if emulated else []
    return ["Constraints"] + E.block_names(n_constraints) + ["Outputs", "Inputs"] + em + ["F", "nWires", "p"]


def battery_prefix(variant: str, n_constraints: int, emulated: bool) -> list[str]:
    if variant in ("V3", "V4"):
        out = ["intro w₁ w₂ h₁ h₂ hin",
               f"(try simp only [{', '.join(['Inputs', 'Outputs'] + (EM_FLATTEN if emulated else []) + E.FLATTEN_LEMMAS)}] at hin ⊢)",
               f"(try unfold {' '.join(['Constraints'] + E.block_names(n_constraints))} at h₁ h₂)"]
        return out + (["repeat' constructor"] if variant == "V4" else [])
    unf = [f"(try unfold {n} at *)" for n in unfold_order(n_constraints, emulated)] + ["(try beta_reduce at *)"]
    if variant == "V0":
        return []
    if variant == "V1":
        return unf
    if variant == "V2":
        return ["intros"] + unf
    raise ValueError(variant)


def emit_battery_forms(ns: str, n_constraints: int, forms: Sequence[tuple[str, str]], heartbeats: int,
                       emulated: bool) -> str:
    lines = ["import Mathlib", "import Std.Tactic.BVDecide", f"import {model_module(ns)}", "",
             f"namespace {ns}", ""]
    for variant, tactic in forms:
        name = E.battery_theorem_name(variant, tactic)
        if variant in ("V3", "V4"):
            lines.append("set_option maxRecDepth 100000 in")
        lines.append(f"set_option maxHeartbeats {heartbeats} in")
        lines.append(f"theorem {name}{theorem_signature(emulated)} := by")
        last = f"all_goals {tactic}" if variant == "V4" else tactic
        lines += [f"  {t}" for t in battery_prefix(variant, n_constraints, emulated) + [last]]
        lines.append(f"#print axioms {name}")
        lines.append("")
    lines += [f"end {ns}", ""]
    return "\n".join(lines)


def emit_fid_runner(ns: str, n_constraints: int, witness_files: Sequence[tuple[str, str]],
                    groups: Sequence[tuple[list[int], int, int]], em_tags: Sequence[str] = ()) -> str:
    """The Circom FID runner (``decide (Constraints w)`` per witness file) plus, for the witnesses in
    ``em_tags``, the value of every emulated output (``emValue w limbs bits % modulus``), so that the
    statement's output relation is checked against the Python evaluation."""
    text = E.emit_fid_runner(ns, n_constraints, witness_files)
    if not groups or not em_tags:
        return text
    extra = ["#eval show IO Unit from do"]
    tags = set(em_tags)
    for tag, path in witness_files:
        if tag not in tags:
            continue
        extra.append(f"  let w ← loadWitness {E._lean_string(path)}")
        extra.append(f"  for g in EmulatedOutputs do IO.println s!\"EMV {tag} {{emValue w g.1 g.2.1 % g.2.2}}\"")
    extra.append("  IO.println \"EMV-DONE\"")
    end = f"end {ns}\n"
    i = text.rindex(end)
    return text[:i] + "\n".join(extra) + "\n\n" + text[i:]
