"""Lean emitters for halo2 DET packages.

The model module transcribes the flattened halo2 model (:mod:`halo2_ir`) of one wrapper circuit over its concrete
layout, in the Circom template's vocabulary so that the statement, the G-FID runner and the checker are shared:

* ``p``, ``F := ZMod p``, ``nWires`` (the advice and instance cells the constraints reference);
* ``Inputs`` / ``Outputs``: literal cell lists (instance cells and named witnessed cells / the wrapper's output
  cells);
* ``Table<k>``: the contents of fixed lookup tables (constants of the circuit); one-column tables that are exactly
  ``{0, .., m-1}`` are stated as ``(x).val < m`` instead;
* ``Constraints w``: every gate instance (polynomial ``= 0``, fixed cells and compressed selectors substituted),
  every copy constraint (``w a = w b`` / ``w a = c``) and every lookup (membership of the input tuple), in
  ``Block<k>`` chunks of :data:`lean_emit.BLOCK`; shared subterms are hoisted into ``t<k> w``.

The statement is the Circom template (theorem ``det``).
"""
from __future__ import annotations

from typing import Sequence

from . import air_ir as AIR
from . import air_lean as AL
from . import halo2_ir as H
from . import lean_emit as E

STATEMENT_THEOREM = E.STATEMENT_THEOREM
LEAN_OPTIONS = E.LEAN_OPTIONS
model_module = E.model_module
model_relpath = E.model_relpath
TABLE_HEARTBEATS = 10000000


def to_air(model: H.Model, name: str = "halo2") -> AIR.Air:
    """The model's polynomial part as an AIR IR object (one-row window, every variable a main cell), for the
    shared term printer and the shared searches.  Copy constraints become ``sub`` nodes."""
    nodes = [list(nd) for nd in model.nodes]
    cons = [k for k, _ in model.polys]
    for a, b, _ in model.copies:
        ks = []
        for o in (a, b):
            ks.append(len(nodes))
            nodes.append(["main", 0, o[1]] if o[0] == "v" else ["const", o[1] % model.p])
        cons.append(len(nodes))
        nodes.append(["sub", ks[0], ks[1]])
    return AIR.Air("halo2", "", "", model.field_name, model.p, name, name, "halo2", 0, max(model.n_vars, 1), 0, 0,
                   nodes, cons, [], {})


def _roots(model: H.Model) -> list[int]:
    roots = [k for k, _ in model.polys] + [k for ins, _, _ in model.lookups for k in ins]
    roots += [k for t in model.tables if t.kind == "advice" for row in t.rows for k in row]
    return roots


def _const(c: int, p: int) -> str:
    return str(c) if c <= p // 2 else f"(-{p - c})"


def used_tables(model: H.Model) -> list[int]:
    return sorted({ti for _, ti, _ in model.lookups if model.tables[ti].kind == "set"})


def items(model: H.Model, pr: AL.Printer) -> list[tuple[str, str]]:
    """(Lean proposition, comment) per constraint item, in model order: gates, copies, lookups."""
    p = model.p
    out = [(f"{pr.term(k)} = 0", label) for k, label in model.polys]
    for a, b, label in model.copies:
        sides = [f"w {o[1]}" if o[0] == "v" else _const(o[1], p) for o in (a, b)]
        out.append((f"{sides[0]} = {sides[1]}", label))
    for ins, ti, label in model.lookups:
        t = model.tables[ti]
        if t.kind == "range":
            out.append((f"({pr.term(ins[0])}).val < {t.bound}", f"{label}, table {ti}: x < {t.bound}"))
        elif t.kind == "set":
            out.append((f"[{', '.join(pr.term(k) for k in ins)}] ∈ Table{ti}", f"{label}, table {ti}"))
        else:
            rows = ", ".join("[" + ", ".join(pr.term(k) for k in row) + "]" for row in t.rows)
            out.append((f"[{', '.join(pr.term(k) for k in ins)}] ∈ [{rows}]", f"{label}, advice table {ti}"))
    return out


def emit_model(ns: str, meta: dict, model: H.Model) -> tuple[str, dict]:
    air = to_air(model)
    layout = AIR.Layout.of(air)
    pr = AL.Printer(air, layout, _roots(model))
    p = model.p
    its = items(model, pr)
    blocks = E.block_names(len(its))
    tabs = used_tables(model)
    header = [
        "import Mathlib",
        "",
        "/-!",
        f"# DET model: {meta['repo_id']} `{meta['target']}` (halo2)",
        "",
        f"Generated by `scripts/zk_registry` ({meta['generator']}); do not edit.",
        "",
        f"* Source: {meta['repo_url']} at `{meta['commit']}`, `{meta['path']}`, `{meta['symbol']}`.",
        f"* Wrapper circuit `{meta['wrapper']}` (rule `{meta['rule']}`): {meta['call']}.",
        f"* Layout: `MockProver::run` of halo2_proofs ({meta['halo2_line']}) at k = {model.k} ({model.n} rows, usable",
        f"  rows 0..{model.usable - 1}); gates after selector compression, as keygen builds them. IR sha256",
        f"  `{meta['ir_sha256']}`; model sha256 `{meta['model_sha256']}`.",
        f"* Field: {model.field_name}, `p = {p}`; `F = ZMod p`.",
        "* `w : Fin nWires → F` assigns the advice and instance cells the constraints reference (below).",
        f"* `Constraints w`: {len(model.polys)} gate instances (polynomial = 0 at a row, fixed cells substituted),",
        f"  {len(model.copies)} copy constraints and {len(model.lookups)} lookups (input tuple in the table over the",
        "  usable rows). Constants are printed balanced (`c > p/2` as `-(p - c)`), which preserves values in `ZMod p`.",
        "* `Inputs`: instance cells" + (" and the cells the wrapper names as witnessed inputs" if model.input_notes
                                       else "") + "; `Outputs`: the wrapper's output cells.",
        "",
        "## Cells",
        "",
    ]
    for v in range(model.n_vars):
        header.append(f"* `w {v}`: {model.cell_name(v)}")
    header += ["-/", "", "set_option maxRecDepth 100000", "", f"namespace {ns}", ""]
    body = [
        f"/-- The {model.field_name} modulus. -/",
        f"abbrev p : ℕ := {p}",
        "",
        "/-- Cell values. -/",
        "abbrev F : Type := ZMod p",
        "",
        "/-- Number of cells of the model. -/",
        f"abbrev nWires : ℕ := {max(model.n_vars, 1)}",
        "",
        *E._long_list_option(model.outputs),
        f"/-- Output cells: {', '.join(model.cell_name(v) for v in model.outputs[:8]) or 'none'}"
        f"{' …' if len(model.outputs) > 8 else ''}. -/",
        f"def Outputs : List (Fin nWires) := [{', '.join(str(v) for v in model.outputs)}]",
        "",
        *E._long_list_option(model.inputs),
        f"/-- Input cells: {', '.join(model.cell_name(v) for v in model.inputs[:8]) or 'none'}"
        f"{' …' if len(model.inputs) > 8 else ''}. -/",
        f"def Inputs : List (Fin nWires) := [{', '.join(str(v) for v in model.inputs)}]",
        "",
    ]
    for ti in tabs:
        t = model.tables[ti]
        rows = ", ".join("[" + ", ".join(_const(x, p) for x in row) + "]" for row in t.rows)
        # a table of ~10^3 tuples of field literals exceeds the default heartbeat budget while elaborating
        body += [f"set_option maxHeartbeats {TABLE_HEARTBEATS} in",
                 f"/-- Lookup table {ti}: the {len(t.rows)} distinct tuples of its fixed table expressions over the "
                 "usable rows (circuit constants). -/", f"def Table{ti} : List (List F) := [{rows}]", ""]
    body += [d.replace("Fin nVars", "Fin nWires") for d in pr.definitions()]

    def conj(chunk):
        lines = []
        for k, (prop, note) in enumerate(chunk):
            sep = " ∧" if k + 1 < len(chunk) else ""
            lines.append(f"  {prop}{sep}  -- {note}")
        return "\n".join(lines)
    if blocks:
        for k, name in enumerate(blocks):
            chunk = its[k * E.BLOCK:(k + 1) * E.BLOCK]
            body += [f"/-- Constraint items {k * E.BLOCK}–{k * E.BLOCK + len(chunk) - 1}. -/",
                     f"def {name} (w : Fin nWires → F) : Prop :=", conj(chunk), ""]
        body += [f"/-- The circuit's constraints over the layout ({len(its)} items). -/",
                 "def Constraints (w : Fin nWires → F) : Prop :=", "  " + " ∧ ".join(f"{b} w" for b in blocks), ""]
    else:
        body += [f"/-- The circuit's constraints over the layout ({len(its)} items). -/",
                 "def Constraints (w : Fin nWires → F) : Prop :=", conj(its) if its else "  True", ""]
    body += [f"end {ns}", ""]
    summary = {"hoisted": pr.hoisted_names(), "blocks": blocks, "tables": [f"Table{ti}" for ti in tabs],
               "n_items": len(its)}
    return "\n".join(header + body), summary


def emit_statement(ns: str, meta: dict) -> str:
    return "\n".join([
        f"import {model_module(ns)}",
        "",
        f"namespace {ns}",
        "",
        f"/-- Output determinism of {meta['repo_id']} `{meta['target']}` ({meta['path']}), halo2 wrapper",
        f"`{meta['wrapper']}`: two cell assignments that satisfy the circuit's gates, copy constraints and lookups",
        "over its layout and agree on every input cell agree on every output cell. -/",
        f"theorem {STATEMENT_THEOREM}{E.theorem_signature()} := by",
        "  sorry",
        "",
        f"end {ns}",
        "",
    ])


def unfold_order(summary: dict) -> list[str]:
    return (["Constraints", *summary["blocks"], *summary["tables"], "Outputs", "Inputs"]
            + list(reversed(summary["hoisted"])) + ["F", "nWires", "p"])


def battery_prefix(variant: str, summary: dict) -> list[str]:
    if variant in ("V3", "V4"):
        out = ["intro w₁ w₂ h₁ h₂ hin",
               f"(try simp only [{', '.join(['Inputs', 'Outputs'] + E.FLATTEN_LEMMAS)}] at hin ⊢)",
               f"(try unfold {' '.join(['Constraints'] + summary['blocks'])} at h₁ h₂)"]
        if summary["hoisted"]:
            out.append(f"(try unfold {' '.join(reversed(summary['hoisted']))} at h₁ h₂)")
        return out + (["repeat' constructor"] if variant == "V4" else [])
    unf = [f"(try unfold {n} at *)" for n in unfold_order(summary)] + ["(try beta_reduce at *)"]
    if variant == "V0":
        return []
    if variant == "V1":
        return unf
    if variant == "V2":
        return ["intros"] + unf
    raise ValueError(variant)


def emit_battery_forms(ns: str, summary: dict, forms: Sequence[tuple[str, str]], heartbeats: int) -> str:
    lines = ["import Mathlib", "import Std.Tactic.BVDecide", f"import {model_module(ns)}", "", f"namespace {ns}", ""]
    for variant, tactic in forms:
        name = E.battery_theorem_name(variant, tactic)
        if variant in ("V3", "V4"):
            lines.append("set_option maxRecDepth 100000 in")
        lines.append(f"set_option maxHeartbeats {heartbeats} in")
        lines.append(f"theorem {name}{E.theorem_signature()} := by")
        last = f"all_goals {tactic}" if variant == "V4" else tactic
        lines += [f"  {t}" for t in battery_prefix(variant, summary) + [last]]
        lines.append(f"#print axioms {name}")
        lines.append("")
    lines += [f"end {ns}", ""]
    return "\n".join(lines)


def emit_fid_runner(ns: str, summary: dict, files: Sequence[tuple[str, str]]) -> str:
    """``decide (Constraints w)`` per witness file (the Circom runner; same block names)."""
    return E.emit_fid_runner(ns, summary["n_items"], files)
