"""Lean model emission for ZoKrates DET packages.

ZoKrates compiles straight to the iden3 R1CS format that the Circom generator already reads
(:mod:`r1cs`), and the model has no tags/preconditions (ZoKrates has no signal-tag system), so this
module only overrides the model header text; the statement, FID runner and TRIV battery emitters are
the shared :mod:`lean_emit` ones, used with ``preconditions=False`` throughout.
"""
from __future__ import annotations

from typing import Sequence

from . import lean_emit as E
from .r1cs import R1cs


def emit_model(ns: str, meta: dict, r: R1cs, outputs: Sequence[int], inputs: Sequence[int],
               wire_names: Sequence[str | None]) -> str:
    p = r.prime
    header = [
        "import Mathlib",
        "",
        "/-!",
        f"# DET model: {meta['repo_id']} `{meta['instantiation']}`",
        "",
        f"Generated by `scripts/zk_registry` ({meta['generator']}); do not edit.",
        "",
        f"* Source: {meta['repo_url']} at `{meta['commit']}`, `{meta['path']}`, symbol `{meta['symbol']}`,",
        f"  instantiation `{meta['instantiation']}` (rule `{meta['rule']}`).",
        f"* Compiled with ZoKrates {meta['zokrates_version']} (`{' '.join(meta['zokrates_flags'])}`).",
        f"* R1CS sha256 `{meta['r1cs_sha256']}`.",
        f"* Field: ZoKrates curve `{meta['prime_name']}`; `F = ZMod p`.",
        "* `w : Fin nWires → F` gives a value to every wire; wire 0 is the constant one.",
        "* `Constraints w` holds iff `w 0 = 1` and every R1CS constraint `(A*w) * (B*w) = C*w` holds.",
        "  Coefficients are printed balanced (`c > p/2` as `-(p - c)`) and a product with an empty",
        "  factor as `0`; both preserve values in `ZMod p`.",
        "* ZoKrates directive/solver outputs that no constraint pins down are not wires of this system",
        "  at all (ZoKrates's own circom-format R1CS writer only allocates a wire for a variable that",
        "  some constraint mentions): they are free in the model, same as an unconstrained hint.",
        "",
        "## Wires",
        "",
    ]
    for wire in range(r.n_wires):
        header.append(f"* `w {wire}`: `{wire_names[wire] or '(unnamed)'}`")
    header += ["-/", "", f"namespace {ns}", ""]
    body = [
        f"/-- The ZoKrates curve's scalar field prime (`{meta['prime_name']}`). -/",
        f"abbrev p : ℕ := {p}",
        "",
        "/-- Signal values. -/",
        "abbrev F : Type := ZMod p",
        "",
        "/-- Number of R1CS wires (wire 0 is the constant one). -/",
        f"abbrev nWires : ℕ := {r.n_wires}",
        "",
        *E._long_list_option(outputs),
        f"/-- Output wires: {E.summarize_names([wire_names[i] or '' for i in outputs])}. -/",
        f"def Outputs : List (Fin nWires) := {E._list_literal(outputs)}",
        "",
        *E._long_list_option(inputs),
        f"/-- Input wires (public and private arguments of the wrapper's `main`): "
        f"{E.summarize_names([wire_names[i] or '' for i in inputs])}. -/",
        f"def Inputs : List (Fin nWires) := {E._list_literal(inputs)}",
        "",
    ]
    cons = [E.render_constraint(a, b, c, p) for a, b, c in r.constraints]
    blocks = E.block_names(len(cons))
    if blocks:
        for k, name in enumerate(blocks):
            chunk = cons[k * E.BLOCK:(k + 1) * E.BLOCK]
            body.append(f"/-- R1CS constraints {k * E.BLOCK}-{k * E.BLOCK + len(chunk) - 1}. -/")
            body.append(f"def {name} (w : Fin nWires → F) : Prop :=")
            body.append(" ∧\n".join(f"  {c}" for c in chunk))
            body.append("")
        body.append(f"/-- The compiled constraint system ({len(cons)} constraints). -/")
        body.append("def Constraints (w : Fin nWires → F) : Prop :=")
        body.append("  w 0 = 1 ∧ " + " ∧ ".join(f"{b} w" for b in blocks))
    else:
        body.append(f"/-- The compiled constraint system ({len(cons)} constraints). -/")
        body.append("def Constraints (w : Fin nWires → F) : Prop :=")
        body.append(" ∧\n".join(["  w 0 = 1"] + [f"  {c}" for c in cons]))
    body += ["", f"end {ns}", ""]
    return "\n".join(header + body)
