d /run/boole 0755 root root -
d /run/boole/native-shadow 2750 root boole-node -
d /var/lib/boole 0755 root root -
d /var/lib/boole/native-shadow 0755 root root -
d /var/lib/boole/native-shadow/node-state 0700 boole-node boole-node -
