#!/usr/bin/env python3
"""Regression tests for P0.4: `boole-node` uses `clap` derive, exposes
`--version`, and the `--help` surface is generated by the parser (not a
hand-rolled `println!` string that drifts from the actual argument set).

L2 contract: every binary's argv layer is typed and self-documenting so
release notes can quote `--help` verbatim without diverging from runtime
behavior."""
from __future__ import annotations

import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NODE_MAIN = ROOT / "crates" / "boole-node" / "src" / "main.rs"
NODE_TOML = ROOT / "crates" / "boole-node" / "Cargo.toml"


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


class ClapDeriveContractTests(unittest.TestCase):
    def test_boole_node_depends_on_clap(self) -> None:
        body = _read(NODE_TOML)
        self.assertRegex(
            body,
            re.compile(r"^\s*clap\b", re.MULTILINE),
            "P0.4: boole-node/Cargo.toml [dependencies] must declare `clap`",
        )

    def test_boole_node_uses_clap_parser_derive(self) -> None:
        body = _read(NODE_MAIN)
        self.assertRegex(
            body,
            re.compile(r"#\[derive\([^)]*\bParser\b[^)]*\)\]", re.MULTILINE),
            "P0.4: boole-node/main.rs must derive `clap::Parser` for the "
            "top-level CLI struct (L2 typed argv)",
        )

    def test_boole_node_does_not_handroll_env_args(self) -> None:
        body = _read(NODE_MAIN)
        # The current handrolled parser uses `std::env::args().skip(1).collect`.
        # After clap migration the dispatch should go through
        # `<Cli as Parser>::parse()` instead.
        self.assertNotRegex(
            body,
            re.compile(r"std::env::args\(\)\.skip\(1\)\.collect", re.MULTILINE),
            "P0.4: boole-node/main.rs must not hand-roll argv parsing after "
            "the clap migration; use `Cli::parse()` instead",
        )

    def test_boole_node_help_not_handrolled(self) -> None:
        body = _read(NODE_MAIN)
        # The current help string is a giant println! literal. After clap
        # migration `--help` is rendered by clap from doc comments on the
        # `Cli` struct, so the literal `fn print_help` should be gone.
        self.assertNotRegex(
            body,
            re.compile(r"^\s*fn\s+print_help\s*\(\s*\)", re.MULTILINE),
            "P0.4: boole-node/main.rs must remove the hand-rolled "
            "`print_help` after clap takes over `--help` rendering",
        )


if __name__ == "__main__":
    unittest.main()
